### ISSUE TITLE
muxer test suite is flaky on CI

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-testing#4]
I haven't seen a single success on travis CI; both go-libp2p-yamux and go-libp2p-mplex tests fail with errors like this:

```
=== RUN   TestYamuxTransport/github.com/libp2p/go-libp2p-testing/suites/mux.SubtestStreamOpenStress
panic: read tcp [::1]:45544->[::1]:37798: use of closed network connection
goroutine 5610 [running]:
github.com/libp2p/go-libp2p-testing/suites/mux.SubtestStreamOpenStress.func1.1()
	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-testing@v0.0.3/suites/mux/muxer_suite.go:336 +0xf2
created by github.com/libp2p/go-libp2p-testing/suites/mux.SubtestStreamOpenStress.func1
	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-testing@v0.0.3/suites/mux/muxer_suite.go:343 +0x180
FAIL	github.com/libp2p/go-libp2p-yamux	30.383s
```

I can never reproduce locally.

**Comment by Stebalien** [comment]
It's hitting the timeout but the panic is causing the test to crash before it can print "timed out receiving streams".
